CREATE SEQUENCE LOCATION_ID_SEQ
MINVALUE 1
START WITH 5
INCREMENT BY 1;

CREATE SEQUENCE PERSON_ID_SEQ
MINVALUE 1
START WITH 4
INCREMENT BY 1;

CREATE SEQUENCE ORGANIZATION_ID_SEQ
MINVALUE 1
START WITH 2
INCREMENT BY 1;

CREATE SEQUENCE OPPORTUNITY_ID_SEQ
MINVALUE 1
START WITH 2
INCREMENT BY 1;

CREATE SEQUENCE COMMITMENT_ID_SEQ
MINVALUE 1
START WITH 2
INCREMENT BY 1;
