create tablespace TEAMLENNY64KB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY64KB.dbf' 
SIZE 64K
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 64K
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY128KB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY128KB.dbf' 
SIZE 128K
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 128K
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY512KB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY512KB.dbf' 
SIZE 512K
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 512K
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY1MB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY1MB.dbf' 
SIZE 1M
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 4M
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY2MB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY2MB.dbf' 
SIZE 2M
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 2M
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY8MB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY8MB.dbf' 
SIZE 8M
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 4M
SEGMENT SPACE MANAGEMENT AUTO;

create tablespace TEAMLENNY16MB 
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/TEAMLENNY16MB.dbf' 
SIZE 16M
EXTENT MANAGEMENT LOCAL 
UNIFORM SIZE 4M
SEGMENT SPACE MANAGEMENT AUTO;