ALTER TABLE VM_CAUSE MOVE 
PCTFREE 0
STORAGE(INITIAL 64K NEXT 64K)
TABLESPACE TEAMLENNY64KB;

ALTER TABLE VM_COMMITMENT MOVE 
PCTFREE 5
STORAGE(INITIAL 4M NEXT 4M) /*STORAGE(INITIAL 565M NEXT 16M)*/ 
TABLESPACE TEAMLENNY16MB;

ALTER TABLE VM_LOCATION MOVE 
PCTFREE 20
STORAGE(INITIAL 4M NEXT 4M) /*STORAGE(INITIAL 504M NEXT 16M)*/
TABLESPACE TEAMLENNY16MB;

ALTER TABLE VM_MEMBER MOVE 
PCTFREE 15
STORAGE(INITIAL 4M NEXT 4M) /*STORAGE(INITIAL 191M NEXT 8M)*/
TABLESPACE TEAMLENNY8MB;

ALTER TABLE VM_MEMCAUSE MOVE 
PCTFREE 0
STORAGE(INITIAL 4M NEXT 4M) /*STORAGE(INITIAL 474M NEXT 16M)*/
TABLESPACE TEAMLENNY16MB;

ALTER TABLE VM_MEMSKILL MOVE 
PCTFREE 0
STORAGE(INITIAL 4M NEXT 4M) /*STORAGE(INITIAL 184M NEXT 8M)*/
TABLESPACE TEAMLENNY8MB;

ALTER TABLE VM_OPPORTUNITY MOVE 
PCTFREE 5
STORAGE(INITIAL 4M NEXT 1M) /*STORAGE(INITIAL 36M NEXT 1M)*/
TABLESPACE TEAMLENNY1MB;

ALTER TABLE VM_OPPSKILL MOVE
PCTFREE 0
STORAGE(INITIAL 4M NEXT 512K) /*STORAGE(INITIAL 17M NEXT 512K)*/
TABLESPACE TEAMLENNY512KB;

ALTER TABLE VM_ORGANIZATION MOVE
PCTFREE 5
STORAGE(INITIAL 4M NEXT 1M) /*STORAGE(INITIAL 35M NEXT 1M)*/
TABLESPACE TEAMLENNY1MB;

ALTER TABLE VM_ORGCAUSE MOVE
PCTFREE 0
STORAGE(INITIAL 4M NEXT 128K) /*STORAGE(INITIAL 7M NEXT 128K)*/
TABLESPACE TEAMLENNY128KB;

ALTER TABLE VM_PERSON MOVE
PCTFREE 10
STORAGE(INITIAL 4M NEXT 512K) /*STORAGE(INITIAL 7M NEXT 512K)*/
TABLESPACE TEAMLENNY512KB;

ALTER TABLE VM_SKILL MOVE
PCTFREE 0
STORAGE(INITIAL 1M NEXT 64K)
TABLESPACE TEAMLENNY64KB;

ALTER TABLE VM_TIMESHEET MOVE
PCTFREE 10
STORAGE(INITIAL 4M NEXT 2M) /*STORAGE(INITIAL 1025M NEXT 2M)*/
TABLESPACE TEAMLENNY2MB