ALTER USER GROUP10 QUOTA 100M ON INDX;

BEGIN
    FOR i IN (SELECT * FROM USER_Indexes WHERE STATUS = 'UNUSABLE' AND INDEX_TYPE = 'NORMAL')
    LOOP
        EXECUTE IMMEDIATE 'ALTER INDEX ' || i.INDEX_NAME || ' REBUILD TABLESPACE INDX';
    END LOOP;
END;